backend:
  name: gitlab
  repo: starrynightstudios/spring-run
  branch: master # Branch to update (optional; defaults to master)
media_folder: "source/images/uploads" # Folder where user uploaded files should go
public_folder: "source" # CMS now knows 'source' is the public folder and will strip this from the path
display_url: https://springrun.com
collections:
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    extension: yml
    format: yml
    files:
      - name: "general"
        label: "Site Settings"
        file: "data/settings.yml"
        description: "General Site Settings"
        fields:
          - {label: "Global title", name: "site_title", widget: "string"}
          - label: "Post Settings"
            name: posts
            widget: "object"
            fields:
              - {label: "Number of posts on frontpage", name: front_limit, widget: number}
              - {label: "Default Author", name: author, widget: string}
              - {label: "Default Thumbnail", name: thumb, widget: image, class: "thumb"}
