backend:
  name: gitlab
  repo: starrynightstudios/spring-run

# images
media_folder: source/images/uploads
public_folder: images/uploads
display_url: https://springrun.com
collections:
  - name: "pages"
    label: "Pages"
    create: true
    folder: 'data/pages'
    extension: yml
    format: yml
    fields:
      - {label: "Page Slug", name: "slug", widget: "string"}
      - {label: "Page Title", name: "title", widget: "string"}
      - {label: "Short Description (SEO)", name: "description", widget: "string"}
      - label: "Sections"
        label_singular: "Section"
        name: "sections"
        widget: "list"
        fields:
          - label: "How to Display Content"
            name: "type"
            widget: "select"
            options:
              - { label: "Single Column (Content only)", value: "content_only" }
              - { label: "Single Column (Images only)", value: "images_only" }
              - { label: "Two Column (Image Left)", value: "images_left" }
              - { label: "Two Column (Image Right)", value: "images_right" }
              - { label: "Page Header", value: "header" }
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}
          - label: "Images"
            name: "images"
            widget: "list"
            required: false
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Display Label", name: "label", widget: "string"}
          - label: "Files and Links"
            name: "files"
            widget: "list"
            required: false
            fields:
              - {label: "File", name: "file", widget: "file", required: "false"}
              - {label: "URL", name: "url", widget: "string", required: "false"}
              - {label: "Display Label", name: "label", widget: "string"}

  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    extension: yml
    format: yml
    files:
      - name: "general"
        label: "Site Settings"
        file: "data/settings.yml"
        description: "General Site Settings"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Subtitle", name: "subtitle", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
      - name: "navigation"
        label: "Top Navigation"
        file: "data/navigation.yml"
        description: "Top Navigation Settings"
        fields:
          - label: "Menu Links"
            label_singular: "Menu Link"
            name: "links"
            widget: "list"
            fields:
              - {label: "Display Label", name: "label", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
      - name: "footer"
        label: "Site Footer"
        file: "data/footer.yml"
        description: "Site Footer Settings"
        fields:
          - label: "Columns"
            label_singular: "Column"
            name: "columns"
            widget: "list"
            fields:
              - {label: "Column Label", name: "label", widget: "string"}
              - {label: "Column Content", name: "content", widget: "markdown"}
      - name: "seo"
        label: "SEO Settings"
        file: "data/seo.yml"
        description: "General SEO Settings"
        fields:
          - {label: "Description", name: "description", widget: "string"}
          - label: "Keywords"
            name: "keywords"
            widget: "list"
            fields:
              - {label: "Keywork", name: "keyword", widget: "string"}
